### ISSUE TITLE
Podman対応

### ISSUE THREAD

**Issue by glatan** [Terfno/ReXeTeXeR#6]
## 要望

現状のMakefileでは、[Podman](https://podman.io/)環境(最新のFedoraとかRHELとか)で動作しない。
[これ](https://gitlab.com/glatan/unofficial-api/-/blob/master/Makefile)みたいにDockerとPodmanの両環境に対応させたい。

## 問題

Docker環境の場合`make init`が`make docker.init`になるなど、若干コマンドが長くなってしまう。

**Comment by Terfno** [comment]
Makefile長くなってもいいので、`$ make init`でdockerが走って、`$ make podman init`するとpodman版が走るような導入が嬉しいです。

**Comment by glatan** [comment]
:ok:

**Comment by Terfno** [comment]
#7 をマージしました。ありがとう。
ドキュメント整備はこっちでやっとくのでCloseで。
