### ISSUE TITLE
Makefile: chmodを削除する

### ISSUE THREAD

**Issue by glatan** [Terfno/ReXeTeXeR#9]
Gitはファイルのパーミッションも管理してくれてるので`make watch`の中で実行権限の付与をする必要はないです。
クローン直後のリポジトリでwatch.shのパーミッションを確認すると、実行権限が付与されているはずです(現状のmasterにて)。

**Comment by Terfno** [comment]
done.
https://github.com/Terfno/ReXeTeXeR/commit/883218c870efaaef83f3b8facf06089a16dd6c39

良さそうならcloseでお願いします。

**Comment by glatan** [comment]
リポジトリ直下の方には残ってるんですがこれは問題ない...?
